enableScripts: true

nodeLinker: node-modules

packageExtensions:
  "ai-sdk-ollama@*":
    peerDependencies:
      zod: "^3.25.76 || ^4.1.8"
  "eslint-plugin-n@*":
    peerDependencies:
      typescript: ">=4.0.0"
