const browserGlobals = Object.fromEntries([
    'AbortController',
    'AbortSignal',
    'Blob',
    'CSS',
    'CustomEvent',
    'DOMParser',
    'Element',
    'Event',
    'EventSource',
    'File',
    'FormData',
    'HTMLElement',
    'HTMLTemplateElement',
    'IntersectionObserver',
    'KeyboardEvent',
    'Location',
    'MutationObserver',
    'Node',
    'ReadableStream',
    'ResizeObserver',
    'Response',
    'TextDecoder',
    'TextEncoder',
    'URL',
    'URLSearchParams',
    'WebSocket',
    'Window',
    'cancelAnimationFrame',
    'clearInterval',
    'clearTimeout',
    'console',
    'customElements',
    'document',
    'fetch',
    'getComputedStyle',
    'history',
    'localStorage',
    'location',
    'performance',
    'requestAnimationFrame',
    'setInterval',
    'setTimeout',
    'window',
].map((name) => [name, 'readonly']));

const projectStyleRules = {
    '@stylistic/arrow-parens': 'off',
    '@stylistic/comma-dangle': 'off',
    '@stylistic/curly-newline': 'off',
    '@stylistic/indent': 'off',
    '@stylistic/keyword-spacing': 'off',
    '@stylistic/max-len': 'off',
    '@stylistic/object-curly-newline': 'off',
    '@stylistic/padding-line-between-statements': 'off',
    'capitalized-comments': 'off',
    camelcase: 'off',
    complexity: 'off',
    curly: 'off',
    'import-x/first': 'off',
    'import-x/no-unassigned-import': 'off',
    'import-x/order': 'off',
    'logical-assignment-operators': 'off',
    'max-lines': 'off',
    'max-params': 'off',
    'max-depth': 'off',
    'n/prefer-global/process': 'off',
    'no-await-in-loop': 'off',
    'no-bitwise': 'off',
    'no-control-regex': 'off',
    'no-implicit-coercion': 'off',
    'no-negated-condition': 'off',
    'no-restricted-globals': 'off',
    'no-return-await': 'off',
    'no-useless-escape': 'off',
    'object-shorthand': 'off',
    'prefer-destructuring': 'off',
    'require-unicode-regexp': 'off',
    'unicorn/better-regex': 'off',
    'unicorn/catch-error-name': 'off',
    'unicorn/explicit-length-check': 'off',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reverse': 'off',
    'unicorn/no-array-sort': 'off',
    'unicorn/no-await-expression-member': 'off',
    'unicorn/no-immediate-mutation': 'off',
    'unicorn/no-for-loop': 'off',
    'unicorn/no-lonely-if': 'off',
    'unicorn/no-new-array': 'off',
    'unicorn/no-negated-condition': 'off',
    'unicorn/no-useless-fallback-in-spread': 'off',
    'unicorn/no-useless-length-check': 'off',
    'unicorn/no-useless-spread': 'off',
    'unicorn/prefer-at': 'off',
    'unicorn/prefer-code-point': 'off',
    'unicorn/prefer-default-parameters': 'off',
    'unicorn/prefer-dom-node-append': 'off',
    'unicorn/prefer-dom-node-dataset': 'off',
    'unicorn/prefer-global-this': 'off',
    'unicorn/prefer-logical-operator-over-ternary': 'off',
    'unicorn/prefer-math-trunc': 'off',
    'unicorn/prefer-modern-dom-apis': 'off',
    'unicorn/prefer-process-exit-code': 'off',
    'unicorn/prefer-query-selector': 'off',
    'unicorn/prefer-single-call': 'off',
    'unicorn/prefer-spread': 'off',
    'unicorn/prefer-string-raw': 'off',
    'unicorn/prefer-string-replace-all': 'off',
    'unicorn/prefer-string-starts-ends-with': 'off',
    'unicorn/prefer-switch': 'off',
    'unicorn/prefer-ternary': 'off',
    'unicorn/prefer-top-level-await': 'off',
    'unicorn/prefer-type-error': 'off',
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/consistent-existence-index-check': 'off',
    'unicorn/numeric-separators-style': 'off',
    'unicorn/no-process-exit': 'off',
    'unicorn/switch-case-braces': 'off',
};

const xoConfig = [
    {
        ignores: [
            'src/fixtures/**',
        ],
    },
    {
        files: [
            '**/*.js',
        ],
        space: 4,
        prettier: 'compat',
        rules: projectStyleRules,
    },
    {
        files: [
            'public/js/**/*.js',
        ],
        languageOptions: {
            globals: browserGlobals,
        },
    },
    {
        // Browser e2e specs run code inside Playwright via page.waitForFunction /
        // page.evaluate, so they reference DOM globals (document, etc.).
        //
        files: [
            'test/browser/**/*.js',
        ],
        languageOptions: {
            globals: browserGlobals,
        },
    },
];

export default xoConfig;
